#   paths.proc - A set of procedures related to paths. It is inspired in
#				 Python packages os.path and pathlib.
#
#   Copyright (C) 2020-2026 Rolando Muñoz A. <rolando.muar@gmail.com>
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program. If not, see <https://www.gnu.org/licenses/>.
#
procedure make_dir: .path$
	@iterate_path: .path$
	for .i to size(iterate_path.return$#)
	    .path$= iterate_path.return$#[.i]
            if .i != 1
				.path$ = "/" + .path$
				createDirectory(.path$)
            endif
	endfor
	writeInfoLine: "adssas"
endproc


procedure iterate_path: .path$
	.objects# = selected#()
	@unixpath: .path$

	# We split the path by "/". Praat's 'Strings' object treats the
    # leading "/" as a delimiter, often omitting the root from the
    # first token.
	.str = Create Strings from tokens: "dirnames", unixpath.return$, "/"
	.nstrings = Get number of strings

	# If the original path was absolute (started with "/"), we manually
    # prepend the slash back to the first directory name to maintain
    # the root.
	if startsWith(unixpath.return$, "/") and .nstrings > 0
		.str$ = Get string: 1
		Set string: 1, "/" + .str$
	endif

	.dirnames$# = empty$#(.nstrings)

	for .i to .nstrings
		.name$ = object$[.str, .i]
		if .i == 1
			.dirnames$#[.i] = .name$
		else
			.dirnames$#[.i] = .dirnames$#[.i-1] + "/" + .name$
		endif
	endfor

	# Clean up the temporary Strings object and restore selection
	removeObject: .str
	selectObject: .objects#
	.return$# = .dirnames$#
endproc


procedure stem_path: .path$
	# Return the basename without the extension of a path.
	#
	# Parameters
	# ----------
	# .path$ : string
	# 	An input path.
	#
	# Return
	# ------
	# string
	# 	The basename without extension.
	#
	@basename: .path$
	@splitext_path: basename.return$
	.return$ = splitext_path.return$#[1]
endproc


procedure swap_extension: .path$, .new_extension$
	# Split a path into a pair (root, ext) such that root + ext == path,
	# and ext is empty or begins with a period and contains at most
	# one period. Leading periods on the basename are ignored.
	#
	# Parameters
	# ----------
	# .path$ : string
	# 	An input path.
	#
	# .new_extension$ : string
	#	The target extension. It must start with "." (e.g. .wav, .TextGrid)
	#
	# Return
	# ------
	# vector : {string, string}
	# 	A vector with two elements: (1) the root path and the
	#  (2) extension.
	#
	@splitext_path: .path$
	.root$ = splitext_path.return$#[1]
	.return$ = .root$ + .new_extension$
endproc


procedure dirname: .path$
	@split_path: .path$
	.return$ = split_path.return$#[1]
endproc


procedure basename: .path$
	@split_path: .path$
	.return$ = split_path.return$#[2]
endproc


procedure join_path: .path$, .paths$#
	# Join one or more path segments intelligently.
	#
	# Parameters
	# ----------
	# .path$ : string
	#	The main path.
	# .items$ : string vector
	# 	The elements to be added into the main path.
	#
	# Return
	# ------
	# string
	#	A path made of the vector elements.
	for .i to size(.paths$#)
		.path$ = .path$ + "/" + .paths$#[.i]
	endfor
	@unixpath: .path$
	.return$ = unixpath.return$
endproc


procedure split_path: .path$
	# Split the pathname path into a pair, (head, tail) where tail is
	# the last pathname component and head is everything leading up to
	# that. The tail part will never contain a slash; if path ends in
	# a slash, tail will be empty.
	#
	# Paremeters
	# ----------
	# .path$ : string
	#	The input path.
	#
	# Returns
	# -------
	# {string, string}
	# 	A 2-vector containing the head and tail of the path.
	#
	@unixpath: .path$
	.normpath$ = unixpath.return$

	if endsWith(.normpath$, "/")
		.head$ = replace_regex$(.normpath$, "(.*)/", "\1", 0)
		.return$# = {.head$, ""}
	else
		.head$ = replace_regex$(.normpath$, "(.*)/(.+)", "\1", 0)
		.tail$ = replace_regex$(.normpath$, "(.*)/(.+)", "\2", 0)
		.return$# = {.head$, .tail$ }
	endif
endproc


procedure splitext_path: .path$
	# Split a path into a pair (root, ext) such that root + ext == path,
	# and ext is empty or begins with a period and contains at most
	# one period. Leading periods on the basename are ignored.
	#
	# Parameters
	# ----------
	# .path$ : string
	# 	An input path.
	#
	# Return
	# ------
	# vector : {string, string}
	# 	A vector with two elements: (1) the root path and the
	#  (2) extension.
	#
	# Examples
	# --------
	# /home/foo/abc.txt -> {"/home/foo/abc", ".txt"}
	# /home/foo/abc.wav.TextGrid -> {"/home/foo/abc.wav", ".TextGrid"}
	# /home/foo/.txt -> {"/home/foo/.txt", ""}
	# /home/foo/abc. -> {"/home/foo/abc.", ""}
	# /home/foo/abc.wav..TextGrid -> {"/home/foo/abc.wav.", ".TextGrid"}
	# /home/foo/..txt -> {"/home/foo/.", ".txt"}
	#
	@unixpath: .path$
	@basename: unixpath.return$
	if index(basename.return$, ".")
		.ext$ = replace_regex$(basename.return$, "(.+)(\..+)", "\2", 0)
		.root$ = unixpath.return$ - .ext$
		if endsWith(.root$, "/")
			.ext$ = ""
			.root$ = unixpath.return$
		endif
	else
		.ext$ = ""
		.root$ = unixpath.return$
	endif
	.return$# = {.root$, .ext$}
endproc


procedure unixpath: .path$
	# On Windows, it converts forward slashes to backward slashes
	.temp_path$ = replace$(.path$, "\", "/", 0)
	.return$ = replace_regex$(.temp_path$, "/+", "/", 0)
endproc


procedure normpath: .path$
	# On Windows, it converts forward slashes to backward slashes
	if windows
		.return$ = replace$(.path$, "/", "\", 0)
	else
		.return$ = replace$(.path$, "\", "/", 0)
	endif
endproc
